package View;

import View.*;
import Controller.DietMaths;
import Controller.MealPlans;
import Controller.Users;
import Models.MealPlan;
import Models.User;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//IT16083424 Perera P.A.H.E     SHU ID=27045240 
/**
 *
 * @author Harshana
 */
public class AdminUI extends javax.swing.JFrame implements Serializable {

        User currentUser;
        Users users = new Users();
        MealPlans mealPlans=new MealPlans();
        MealPlan currentMealPlan;
        

    /**
     * Creates new form View
     */
    public AdminUI() {
        initComponents();
        DeserializeUsers();
        DeserializeMealPlans();
        populateUsersList();
        populateMeanPlanList();

    }
       /**
     * Serialize Users
     */
    public void SerializeUser() {
        try {
            FileOutputStream ufos = new FileOutputStream(new File("users.txt"));
            ObjectOutputStream uboos = new ObjectOutputStream(ufos);
            uboos.writeObject(users);
            uboos.flush();
            uboos.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
      /**
     * Deserialize Users
     */
    public void DeserializeUsers() {
        ObjectInputStream uois = null;
        File file = new File("users.txt");
        try {

            FileInputStream ufis = new FileInputStream(file);
            if (ufis.available() != 0) {
                uois = new ObjectInputStream(ufis);
                while (uois != null) {
                    users = (Users) uois.readObject();
                    System.out.println(this.users.size());
                }
            }
        } catch (Exception e) {

        }
    }
    /**
     * SerializeMealPlans
     */
    
     public void SerializeMealPlans() {
        try {
            FileOutputStream mplfos = new FileOutputStream(new File("mealPlans.txt"));
            ObjectOutputStream mplboos = new ObjectOutputStream(mplfos);
            mplboos.writeObject(mealPlans);
            mplboos.flush();
            mplboos.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
     /**
     * Deserialize Users
     */
    public void DeserializeMealPlans() {
        ObjectInputStream mplois = null;
        File file = new File("mealPlans.txt");
        try {

            FileInputStream mplfis = new FileInputStream(file);
            if (mplfis.available() != 0) {
                mplois = new ObjectInputStream(mplfis);
                while (mplois != null) {
                    mealPlans = (MealPlans) mplois.readObject();
                    System.out.println(this.mealPlans.size());
                }
            }
        } catch (Exception e) {

        }
    }
    
    
     private void populateUsersList() {
        DefaultTableModel dtm = (DefaultTableModel) tblUserMgt.getModel();
        dtm.setRowCount(0);
        for (User user : users) {
            Vector v = new Vector();
            v.add(user.getName());
            v.add(user.getEmail());
            v.add(user.getAge());
            v.add(user.getHeight());
            v.add(user.getWeight());
            v.add(user.getGender());
           
            dtm.addRow(v);
        }
    }
     
     private void populateMeanPlanList() {
        DefaultTableModel dtm = (DefaultTableModel) tblManageMealPlans.getModel();
        dtm.setRowCount(0);
        for (MealPlan mealPlan : mealPlans) {
            Vector v = new Vector();
            v.add(mealPlan.getId());
            v.add(mealPlan.getName());
            v.add(mealPlan.getCalorieAmount());
            v.add(mealPlan.getBreakfast());
            v.add(mealPlan.getLunch());
            v.add(mealPlan.getDinner());
            v.add(mealPlan.getSnack());
            dtm.addRow(v);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radGrpGender = new javax.swing.ButtonGroup();
        jTabbedPaneMainPanelAdmin = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblViewMealPlans = new javax.swing.JTable();
        jSeparator22 = new javax.swing.JSeparator();
        txtSearchMealView = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        btnSearchMealPlanView = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jSeparator20 = new javax.swing.JSeparator();
        txtFoodName1 = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        txtFoodCalorieAmount1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btnAddMealPlan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBreakfastManageMealPlan = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLunchManageMealPlan = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtDinnerManageMealPlan = new javax.swing.JTextArea();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtSnackManageMealPlan = new javax.swing.JTextArea();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblManageMealPlans = new javax.swing.JTable();
        btnRemoveMealPlan = new javax.swing.JButton();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        txtSearchMealManage = new javax.swing.JTextField();
        btnSearchManageMealPlan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblUserMgt = new javax.swing.JTable();
        jSeparator24 = new javax.swing.JSeparator();
        txtSearchMealView1 = new javax.swing.JTextField();
        btnSearchUser = new javax.swing.JButton();
        cmbSearchUser = new javax.swing.JComboBox<>();
        btnRemoveUser = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(32, 33, 35));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPaneMainPanelAdmin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(32, 33, 35));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jPanel11.setBackground(new java.awt.Color(32, 33, 35));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblViewMealPlans.setBackground(new java.awt.Color(32, 33, 35));
        tblViewMealPlans.setForeground(new java.awt.Color(255, 255, 255));
        tblViewMealPlans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Meal Plan Name", "Total Calories", "Breakfast", "Lunch", "Dinner", "Snack"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tblViewMealPlans);

        jPanel11.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1180, 410));

        jSeparator22.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 160, 10));

        txtSearchMealView.setBackground(new java.awt.Color(32, 33, 35));
        txtSearchMealView.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtSearchMealView.setForeground(new java.awt.Color(255, 255, 255));
        txtSearchMealView.setBorder(null);
        jPanel11.add(txtSearchMealView, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 160, 20));

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Enter Meal Plan Name:");
        jPanel11.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, -1));

        btnSearchMealPlanView.setBackground(new java.awt.Color(38, 50, 56));
        btnSearchMealPlanView.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSearchMealPlanView.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchMealPlanView.setText("Search Meal Plan");
        btnSearchMealPlanView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMealPlanViewActionPerformed(evt);
            }
        });
        jPanel11.add(btnSearchMealPlanView, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 180, -1));

        jTabbedPane5.addTab("                                             View Meal Plans                                          ", jPanel11);

        jPanel5.setBackground(new java.awt.Color(32, 33, 35));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator20.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator20.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 160, 10));

        txtFoodName1.setBackground(new java.awt.Color(32, 33, 35));
        txtFoodName1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtFoodName1.setForeground(new java.awt.Color(255, 255, 255));
        txtFoodName1.setBorder(null);
        jPanel5.add(txtFoodName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 160, 20));

        jSeparator21.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator21.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 170, 10));

        txtFoodCalorieAmount1.setBackground(new java.awt.Color(32, 33, 35));
        txtFoodCalorieAmount1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtFoodCalorieAmount1.setForeground(new java.awt.Color(255, 255, 255));
        txtFoodCalorieAmount1.setBorder(null);
        jPanel5.add(txtFoodCalorieAmount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 170, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Total Calorie Amount:");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 150, -1));

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Breakfast:");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, -1));

        btnAddMealPlan.setBackground(new java.awt.Color(38, 50, 56));
        btnAddMealPlan.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnAddMealPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMealPlan.setText("Add Meal Plan");
        btnAddMealPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMealPlanActionPerformed(evt);
            }
        });
        jPanel5.add(btnAddMealPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 130, 140, -1));

        txtBreakfastManageMealPlan.setColumns(20);
        txtBreakfastManageMealPlan.setRows(5);
        jScrollPane1.setViewportView(txtBreakfastManageMealPlan);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 240, 150));

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Meal Plan Name:");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, -1));

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Lunch:");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 80, -1));

        txtLunchManageMealPlan.setColumns(20);
        txtLunchManageMealPlan.setRows(5);
        jScrollPane2.setViewportView(txtLunchManageMealPlan);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 240, 150));

        txtDinnerManageMealPlan.setColumns(20);
        txtDinnerManageMealPlan.setRows(5);
        jScrollPane7.setViewportView(txtDinnerManageMealPlan);

        jPanel5.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 240, 150));

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Dinner:");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 80, -1));

        txtSnackManageMealPlan.setColumns(20);
        txtSnackManageMealPlan.setRows(5);
        jScrollPane8.setViewportView(txtSnackManageMealPlan);

        jPanel5.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 240, 150));

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Snack:");
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 80, -1));

        tblManageMealPlans.setBackground(new java.awt.Color(32, 33, 35));
        tblManageMealPlans.setForeground(new java.awt.Color(255, 255, 255));
        tblManageMealPlans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MPID", "Meal Plan Name", "Total Calories", "Breakfast", "Lunch", "Dinner", "Snack"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblManageMealPlans);

        jPanel5.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 1180, 190));

        btnRemoveMealPlan.setBackground(new java.awt.Color(38, 50, 56));
        btnRemoveMealPlan.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnRemoveMealPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveMealPlan.setText("Remove Meal Plan");
        btnRemoveMealPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveMealPlanActionPerformed(evt);
            }
        });
        jPanel5.add(btnRemoveMealPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 460, 190, -1));

        jSeparator23.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator23.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 160, 10));

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Enter Meal Plan Name:");
        jPanel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 170, -1));

        txtSearchMealManage.setBackground(new java.awt.Color(32, 33, 35));
        txtSearchMealManage.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtSearchMealManage.setForeground(new java.awt.Color(255, 255, 255));
        txtSearchMealManage.setBorder(null);
        jPanel5.add(txtSearchMealManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 160, 20));

        btnSearchManageMealPlan.setBackground(new java.awt.Color(38, 50, 56));
        btnSearchManageMealPlan.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSearchManageMealPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchManageMealPlan.setText("Search Meal Plan");
        btnSearchManageMealPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchManageMealPlanActionPerformed(evt);
            }
        });
        jPanel5.add(btnSearchManageMealPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 180, -1));

        jTabbedPane5.addTab("                                         Manage Meal Plans                                         ", jPanel5);

        jPanel3.add(jTabbedPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 550));

        jTabbedPaneMainPanelAdmin.addTab("                      Meal Plan                     ", jPanel3);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUserMgt.setBackground(new java.awt.Color(32, 33, 35));
        tblUserMgt.setForeground(new java.awt.Color(255, 255, 255));
        tblUserMgt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Age", "Height", "Weight", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(tblUserMgt);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1180, 390));

        jSeparator24.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator24.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 160, 10));

        txtSearchMealView1.setBackground(new java.awt.Color(32, 33, 35));
        txtSearchMealView1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtSearchMealView1.setForeground(new java.awt.Color(255, 255, 255));
        txtSearchMealView1.setBorder(null);
        jPanel1.add(txtSearchMealView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 160, 20));

        btnSearchUser.setBackground(new java.awt.Color(38, 50, 56));
        btnSearchUser.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSearchUser.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchUser.setText("Search User");
        btnSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 180, -1));

        cmbSearchUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option to Search", "Search By Name", "Search By Email" }));
        jPanel1.add(cmbSearchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnRemoveUser.setBackground(new java.awt.Color(38, 50, 56));
        btnRemoveUser.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnRemoveUser.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveUser.setText("Remove User");
        btnRemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemoveUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 480, 190, -1));

        jTabbedPaneMainPanelAdmin.addTab("              User Management               ", jPanel1);

        jPanel4.setBackground(new java.awt.Color(32, 33, 35));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Set API Key");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, -1));

        jTabbedPaneMainPanelAdmin.addTab("Settings", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jTabbedPaneMainPanelAdmin.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Images/SignOut.png")), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMainPanelAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneMainPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jTabbedPaneMainPanelAdmin.getAccessibleContext().setAccessibleName("     Me     ");

        setSize(new java.awt.Dimension(1222, 585));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        SerializeUser();
        SerializeMealPlans();
        
    }//GEN-LAST:event_formWindowClosing

    private void btnAddMealPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMealPlanActionPerformed
//Integer(tx.toString)-set text
        String mealPlanName=txtFoodName1.getText();
        double totalCalorieAmount=Double.parseDouble(txtFoodCalorieAmount1.getText());
        String breakfast=txtBreakfastManageMealPlan.getText();
        String lunch=txtLunchManageMealPlan.getText();
        String dinner=txtDinnerManageMealPlan.getText();
        String snack=txtSnackManageMealPlan.getText();
        
        currentMealPlan=new MealPlan(mealPlanName,totalCalorieAmount,breakfast,lunch,dinner,snack);
        mealPlans.addMealPlan(currentMealPlan);
        populateMeanPlanList();
    }//GEN-LAST:event_btnAddMealPlanActionPerformed

    private void btnRemoveMealPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveMealPlanActionPerformed
//         int yesNo = JOptionPane.showConfirmDialog(null, "Do you really want to remove Meal Plan?", " Remove Meal Plan ", JOptionPane.YES_NO_OPTION);
//         if (yesNo == 0) {
//              DefaultTableModel d = (DefaultTableModel) tblUserMgt.getModel();
//               int i = tblUserMgt.getSelectedRow(); 
//               String email=d.getValueAt(0, 1).toString();
//               //System.out.println("email of selected user"+email);
//               currentUser=users.getUserByEmail(email);
//              // System.out.println("selected currentUser"+currentUser);
//               users.removeUser(currentUser);
//               populateUsersList();
//         }
//            



    }//GEN-LAST:event_btnRemoveMealPlanActionPerformed

    private void btnSearchMealPlanViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMealPlanViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchMealPlanViewActionPerformed

    private void btnSearchManageMealPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchManageMealPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchManageMealPlanActionPerformed

    private void btnSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUserActionPerformed
            String searchKey = txtSearchMealView1.getText();
            
             if (cmbSearchUser.getSelectedIndex() == 0) {
                 populateUsersList();
                 //clearText();
                 }
             if(cmbSearchUser.getSelectedIndex() == 1){
                 
                 System.out.println("user by name"+ users.getUserByName(searchKey).size());
                  DefaultTableModel dtm = (DefaultTableModel) tblUserMgt.getModel();
                    dtm.setRowCount(0);
                     for (int i = 0; i < users.getUserByName(searchKey).size(); i++) {
                User user = users.getUserByName(searchKey).get(i);
                Vector v = new Vector();
                v.add(user.getName());
                v.add(user.getEmail());
                v.add(user.getAge());
                v.add(user.getHeight());
                v.add(user.getWeight());
                v.add(user.getGender());

                
               
                dtm.addRow(v);
            }
                    
                    
             }
             
             
             
             if(cmbSearchUser.getSelectedIndex() == 2){
                 try {
                   //  users.getUserByEmail(searchKey);
                     DefaultTableModel dtm = (DefaultTableModel) tblUserMgt.getModel();
                     dtm.setRowCount(0);
                        Vector v = new Vector();
                        v.add(users.getUserByEmail(searchKey).getName());
                        v.add(users.getUserByEmail(searchKey).getEmail());
                        v.add(users.getUserByEmail(searchKey).getAge());
                        v.add(users.getUserByEmail(searchKey).getHeight());
                        v.add(users.getUserByEmail(searchKey).getWeight());
                        v.add(users.getUserByEmail(searchKey).getGender());
                        dtm.addRow(v);
                    } catch (Exception e) {
                 }
             }
             
             
             
             
    }//GEN-LAST:event_btnSearchUserActionPerformed

    private void btnRemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveUserActionPerformed
        int yesNo = JOptionPane.showConfirmDialog(null, "Do you really want to remove User?", " Remove User ", JOptionPane.YES_NO_OPTION);
         if (yesNo == 0) {
              DefaultTableModel d = (DefaultTableModel) tblUserMgt.getModel();
               int i = tblUserMgt.getSelectedRow(); 
               String email=d.getValueAt(0, 1).toString();
               //System.out.println("email of selected user"+email);
               currentUser=users.getUserByEmail(email);
              // System.out.println("selected currentUser"+currentUser);
               users.removeUser(currentUser);
               populateUsersList();
         }



    }//GEN-LAST:event_btnRemoveUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMealPlan;
    private javax.swing.JButton btnRemoveMealPlan;
    private javax.swing.JButton btnRemoveUser;
    private javax.swing.JButton btnSearchManageMealPlan;
    private javax.swing.JButton btnSearchMealPlanView;
    private javax.swing.JButton btnSearchUser;
    private javax.swing.JComboBox<String> cmbSearchUser;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPaneMainPanelAdmin;
    private javax.swing.ButtonGroup radGrpGender;
    private javax.swing.JTable tblManageMealPlans;
    private javax.swing.JTable tblUserMgt;
    private javax.swing.JTable tblViewMealPlans;
    private javax.swing.JTextArea txtBreakfastManageMealPlan;
    private javax.swing.JTextArea txtDinnerManageMealPlan;
    private javax.swing.JTextField txtFoodCalorieAmount1;
    private javax.swing.JTextField txtFoodName1;
    private javax.swing.JTextArea txtLunchManageMealPlan;
    private javax.swing.JTextField txtSearchMealManage;
    private javax.swing.JTextField txtSearchMealView;
    private javax.swing.JTextField txtSearchMealView1;
    private javax.swing.JTextArea txtSnackManageMealPlan;
    // End of variables declaration//GEN-END:variables

}
