package View;
import View.*;
import Controller.DietMaths;
import java.io.Serializable;

//IT16083424 Perera P.A.H.E     SHU ID=27045240 
/**
 *
 * @author Harshana
 */
public class AdminUI extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form View
     */
    public AdminUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radGrpGender = new javax.swing.ButtonGroup();
        jTabbedPaneMainPanelAdmin = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblViewFoods = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jSeparator14 = new javax.swing.JSeparator();
        txtFoodName = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        txtFoodCalorieAmount = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        txtFoodCarbsAmount = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        txtFoodFatAmount = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        txtFoodProteinAmount = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnRemoveFood = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblManageFoods = new javax.swing.JTable();
        btnAddFood = new javax.swing.JButton();
        jcbSnack = new javax.swing.JCheckBox();
        jcbBreakfast = new javax.swing.JCheckBox();
        jcbLunch = new javax.swing.JCheckBox();
        jcbDinner = new javax.swing.JCheckBox();
        jSeparator19 = new javax.swing.JSeparator();
        txtSearchFoodName = new javax.swing.JTextField();
        btnSearchFoodInManageFood = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(32, 33, 35));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPaneMainPanelAdmin.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        jTabbedPane4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jPanel10.setBackground(new java.awt.Color(32, 33, 35));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblViewFoods.setBackground(new java.awt.Color(32, 33, 35));
        tblViewFoods.setForeground(new java.awt.Color(255, 255, 255));
        tblViewFoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Name", "Calories", "Carbs", "Fat", "Protein"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblViewFoods);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 1180, 440));

        jTabbedPane4.addTab("                                             View Foods                                          ", jPanel10);

        jPanel2.setBackground(new java.awt.Color(32, 33, 35));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator14.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 10));

        txtFoodName.setBackground(new java.awt.Color(32, 33, 35));
        txtFoodName.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtFoodName.setForeground(new java.awt.Color(255, 255, 255));
        txtFoodName.setBorder(null);
        jPanel2.add(txtFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Can be consumed for:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 160, -1));

        jSeparator15.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 90, 10));

        txtFoodCalorieAmount.setBackground(new java.awt.Color(32, 33, 35));
        txtFoodCalorieAmount.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtFoodCalorieAmount.setForeground(new java.awt.Color(255, 255, 255));
        txtFoodCalorieAmount.setBorder(null);
        jPanel2.add(txtFoodCalorieAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 90, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Calories:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 70, -1));

        jSeparator16.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 90, 10));

        txtFoodCarbsAmount.setBackground(new java.awt.Color(32, 33, 35));
        txtFoodCarbsAmount.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtFoodCarbsAmount.setForeground(new java.awt.Color(255, 255, 255));
        txtFoodCarbsAmount.setBorder(null);
        jPanel2.add(txtFoodCarbsAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 90, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Carbs:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 50, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Fat:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 30, -1));

        jSeparator17.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 90, 10));

        txtFoodFatAmount.setBackground(new java.awt.Color(32, 33, 35));
        txtFoodFatAmount.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtFoodFatAmount.setForeground(new java.awt.Color(255, 255, 255));
        txtFoodFatAmount.setBorder(null);
        jPanel2.add(txtFoodFatAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 90, -1));

        jSeparator18.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 90, 10));

        txtFoodProteinAmount.setBackground(new java.awt.Color(32, 33, 35));
        txtFoodProteinAmount.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtFoodProteinAmount.setForeground(new java.awt.Color(255, 255, 255));
        txtFoodProteinAmount.setBorder(null);
        jPanel2.add(txtFoodProteinAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 90, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Protein:");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 60, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Food Name:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        btnRemoveFood.setBackground(new java.awt.Color(38, 50, 56));
        btnRemoveFood.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnRemoveFood.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveFood.setText("Remove Food");
        btnRemoveFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFoodActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemoveFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 450, 140, -1));

        tblManageFoods.setBackground(new java.awt.Color(32, 33, 35));
        tblManageFoods.setForeground(new java.awt.Color(255, 255, 255));
        tblManageFoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Name", "Calories", "Carbs", "Fat", "Protein"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblManageFoods);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1180, 270));

        btnAddFood.setBackground(new java.awt.Color(38, 50, 56));
        btnAddFood.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnAddFood.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFood.setText("Add Food");
        btnAddFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFoodActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 130, 120, -1));

        jcbSnack.setForeground(new java.awt.Color(255, 255, 255));
        jcbSnack.setText("Snacks");
        jcbSnack.setBorder(null);
        jcbSnack.setContentAreaFilled(false);
        jPanel2.add(jcbSnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 100, 90, -1));

        jcbBreakfast.setForeground(new java.awt.Color(255, 255, 255));
        jcbBreakfast.setText("Breakfast");
        jcbBreakfast.setBorder(null);
        jcbBreakfast.setContentAreaFilled(false);
        jPanel2.add(jcbBreakfast, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 90, -1));

        jcbLunch.setForeground(new java.awt.Color(255, 255, 255));
        jcbLunch.setText("Lunch");
        jcbLunch.setBorder(null);
        jcbLunch.setContentAreaFilled(false);
        jPanel2.add(jcbLunch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, 90, -1));

        jcbDinner.setForeground(new java.awt.Color(255, 255, 255));
        jcbDinner.setText("Dinner");
        jcbDinner.setBorder(null);
        jcbDinner.setContentAreaFilled(false);
        jPanel2.add(jcbDinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 70, 90, -1));

        jSeparator19.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator19.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, 10));

        txtSearchFoodName.setBackground(new java.awt.Color(32, 33, 35));
        txtSearchFoodName.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtSearchFoodName.setForeground(new java.awt.Color(255, 255, 255));
        txtSearchFoodName.setBorder(null);
        jPanel2.add(txtSearchFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, -1));

        btnSearchFoodInManageFood.setBackground(new java.awt.Color(38, 50, 56));
        btnSearchFoodInManageFood.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnSearchFoodInManageFood.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchFoodInManageFood.setText("Search Food");
        btnSearchFoodInManageFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFoodInManageFoodActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearchFoodInManageFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, -1));

        jTabbedPane4.addTab("                                         Manage Foods                                         ", jPanel2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPaneMainPanelAdmin.addTab("           Foods          ", jPanel6);

        jPanel3.setBackground(new java.awt.Color(32, 33, 35));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPaneMainPanelAdmin.addTab("      Meal Plan      ", jPanel3);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Set API Key");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, -1));

        jTabbedPaneMainPanelAdmin.addTab("    Settings   ", jPanel1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        jTabbedPaneMainPanelAdmin.addTab("", new javax.swing.ImageIcon(getClass().getResource("/Images/SignOut.png")), jPanel4); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMainPanelAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneMainPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jTabbedPaneMainPanelAdmin.getAccessibleContext().setAccessibleName("     Me     ");

        setSize(new java.awt.Dimension(1222, 585));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void btnRemoveFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFoodActionPerformed

    }//GEN-LAST:event_btnRemoveFoodActionPerformed

    private void btnAddFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddFoodActionPerformed

    private void btnSearchFoodInManageFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFoodInManageFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchFoodInManageFoodActionPerformed

    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFood;
    private javax.swing.JButton btnRemoveFood;
    private javax.swing.JButton btnSearchFoodInManageFood;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPaneMainPanelAdmin;
    private javax.swing.JCheckBox jcbBreakfast;
    private javax.swing.JCheckBox jcbDinner;
    private javax.swing.JCheckBox jcbLunch;
    private javax.swing.JCheckBox jcbSnack;
    private javax.swing.ButtonGroup radGrpGender;
    private javax.swing.JTable tblManageFoods;
    private javax.swing.JTable tblViewFoods;
    private javax.swing.JTextField txtFoodCalorieAmount;
    private javax.swing.JTextField txtFoodCarbsAmount;
    private javax.swing.JTextField txtFoodFatAmount;
    private javax.swing.JTextField txtFoodName;
    private javax.swing.JTextField txtFoodProteinAmount;
    private javax.swing.JTextField txtSearchFoodName;
    // End of variables declaration//GEN-END:variables

}
